name: Node.js CI with Git LFS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 确保检出完整的历史记录
    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs fetch --all
        git lfs checkout
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./dist
